sudo: false

language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7

os:
  - linux

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - compile
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: release
	  node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh
