sudo: false

language: node_js

node_js: 10

os: linux

cache:
  directories: node_modules

notifications:
  email: false

stages:
  - compile
  - name: release
    if: branch = master AND type = push AND fork = false
  - deploy

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: release
      script: .travis/release.sh

    - stage: deploy
      script: .travis/deploy.sh
