sudo: false

language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7

os:
  - linux

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - compile
  - name: deploy
	if: branch = master AND type = push AND fork = false
  - release

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: deploy
      node_js: 10
      script: .travis/deploy.sh

	- stage: release
      node_js: 10
      script: .travis/webhook.sh
