sudo: false

language: node_js

node_js:
  - 10

os:
  - linux

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - compile
  - name: deploy
    if: branch = master AND type = push AND fork = false
  - release

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: deploy
      script: .travis/deploy.sh

    - stage: release
      script: .travis/webhook.sh
