sudo: false

language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7

os:
  - linux

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - compile
  - test
  - name: deploy
    if: branch = master AND type = push AND fork = false
  - name: webhook
    if: branch = master AND type = push AND fork = false AND tags = true

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: deploy
	  node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh

    - stage: webhook
	  script: bash scripts/webhook.sh
