sudo: false

language: node_js

node_js:
  - 10
  - 9
  - 8

os:
  - linux

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - compile
  - name: release
    if: branch = master

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh
