const timezones = [
	{ value: "(GMT-11:00) Niue", key: "Pacific/Niue" },
	{ value: "(GMT-11:00) Pago Pago", key: "Pacific/Pago_Pago" },
	{ value: "(GMT-10:00) Hawaii Time", key: "Pacific/Honolulu" },
	{ value: "(GMT-10:00) Rarotonga", key: "Pacific/Rarotonga" },
	{ value: "(GMT-10:00) Tahiti", key: "Pacific/Tahiti" },
	{ value: "(GMT-09:30) Marquesas", key: "Pacific/Marquesas" },
	{ value: "(GMT-09:00) Alaska Time", key: "America/Anchorage" },
	{ value: "(GMT-09:00) Gambier", key: "Pacific/Gambier" },
	{ value: "(GMT-08:00) Pacific Time", key: "America/Los_Angeles" },
	{ value: "(GMT-08:00) Pacific Time - Tijuana", key: "America/Tijuana" },
	{ value: "(GMT-08:00) Pacific Time - Vancouver", key: "America/Vancouver" },
	{ value: "(GMT-08:00) Pacific Time - Whitehorse", key: "America/Whitehorse" },
	{ value: "(GMT-08:00) Pitcairn", key: "Pacific/Pitcairn" },
	{ value: "(GMT-07:00) Mountain Time", key: "America/Denver" },
	{ value: "(GMT-07:00) Mountain Time - Arizona", key: "America/Phoenix" },
	{ value: "(GMT-07:00) Mountain Time - Chihuahua, Mazatlan", key: "America/Mazatlan" },
	{ value: "(GMT-07:00) Mountain Time - Dawson Creek", key: "America/Dawson_Creek" },
	{ value: "(GMT-07:00) Mountain Time - Edmonton", key: "America/Edmonton" },
	{ value: "(GMT-07:00) Mountain Time - Hermosillo", key: "America/Hermosillo" },
	{ value: "(GMT-07:00) Mountain Time - Yellowknife", key: "America/Yellowknife" },
	{ value: "(GMT-06:00) Belize", key: "America/Belize" },
	{ value: "(GMT-06:00) Central Time", key: "America/Chicago" },
	{ value: "(GMT-06:00) Central Time - Mexico City", key: "America/Mexico_City" },
	{ value: "(GMT-06:00) Central Time - Regina", key: "America/Regina" },
	{ value: "(GMT-06:00) Central Time - Tegucigalpa", key: "America/Tegucigalpa" },
	{ value: "(GMT-06:00) Central Time - Winnipeg", key: "America/Winnipeg" },
	{ value: "(GMT-06:00) Costa Rica", key: "America/Costa_Rica" },
	{ value: "(GMT-06:00) El Salvador", key: "America/El_Salvador" },
	{ value: "(GMT-06:00) Galapagos", key: "Pacific/Galapagos" },
	{ value: "(GMT-06:00) Guatemala", key: "America/Guatemala" },
	{ value: "(GMT-06:00) Managua", key: "America/Managua" },
	{ value: "(GMT-05:00) America Cancun", key: "America/Cancun" },
	{ value: "(GMT-05:00) Bogota", key: "America/Bogota" },
	{ value: "(GMT-05:00) Easter Island", key: "Pacific/Easter" },
	{ value: "(GMT-05:00) Eastern Time", key: "America/New_York" },
	{ value: "(GMT-05:00) Eastern Time - Iqaluit", key: "America/Iqaluit" },
	{ value: "(GMT-05:00) Eastern Time - Toronto", key: "America/Toronto" },
	{ value: "(GMT-05:00) Guayaquil", key: "America/Guayaquil" },
	{ value: "(GMT-05:00) Havana", key: "America/Havana" },
	{ value: "(GMT-05:00) Jamaica", key: "America/Jamaica" },
	{ value: "(GMT-05:00) Lima", key: "America/Lima" },
	{ value: "(GMT-05:00) Nassau", key: "America/Nassau" },
	{ value: "(GMT-05:00) Panama", key: "America/Panama" },
	{ value: "(GMT-05:00) Port-au-Prince", key: "America/Port-au-Prince" },
	{ value: "(GMT-05:00) Rio Branco", key: "America/Rio_Branco" },
	{ value: "(GMT-04:00) Atlantic Time - Halifax", key: "America/Halifax" },
	{ value: "(GMT-04:00) Barbados", key: "America/Barbados" },
	{ value: "(GMT-04:00) Bermuda", key: "Atlantic/Bermuda" },
	{ value: "(GMT-04:00) Boa Vista", key: "America/Boa_Vista" },
	{ value: "(GMT-04:00) Caracas", key: "America/Caracas" },
	{ value: "(GMT-04:00) Curacao", key: "America/Curacao" },
	{ value: "(GMT-04:00) Grand Turk", key: "America/Grand_Turk" },
	{ value: "(GMT-04:00) Guyana", key: "America/Guyana" },
	{ value: "(GMT-04:00) La Paz", key: "America/La_Paz" },
	{ value: "(GMT-04:00) Manaus", key: "America/Manaus" },
	{ value: "(GMT-04:00) Martinique", key: "America/Martinique" },
	{ value: "(GMT-04:00) Port of Spain", key: "America/Port_of_Spain" },
	{ value: "(GMT-04:00) Porto Velho", key: "America/Porto_Velho" },
	{ value: "(GMT-04:00) Puerto Rico", key: "America/Puerto_Rico" },
	{ value: "(GMT-04:00) Santo Domingo", key: "America/Santo_Domingo" },
	{ value: "(GMT-04:00) Thule", key: "America/Thule" },
	{ value: "(GMT-03:30) Newfoundland Time - St. Johns", key: "America/St_Johns" },
	{ value: "(GMT-03:00) Araguaina", key: "America/Araguaina" },
	{ value: "(GMT-03:00) Asuncion", key: "America/Asuncion" },
	{ value: "(GMT-03:00) Belem", key: "America/Belem" },
	{ value: "(GMT-03:00) Buenos Aires", key: "America/Argentina/Buenos_Aires" },
	{ value: "(GMT-03:00) Campo Grande", key: "America/Campo_Grande" },
	{ value: "(GMT-03:00) Cayenne", key: "America/Cayenne" },
	{ value: "(GMT-03:00) Cuiaba", key: "America/Cuiaba" },
	{ value: "(GMT-03:00) Fortaleza", key: "America/Fortaleza" },
	{ value: "(GMT-03:00) Godthab", key: "America/Godthab" },
	{ value: "(GMT-03:00) Maceio", key: "America/Maceio" },
	{ value: "(GMT-03:00) Miquelon", key: "America/Miquelon" },
	{ value: "(GMT-03:00) Montevideo", key: "America/Montevideo" },
	{ value: "(GMT-03:00) Palmer", key: "Antarctica/Palmer" },
	{ value: "(GMT-03:00) Paramaribo", key: "America/Paramaribo" },
	{ value: "(GMT-03:00) Punta Arenas", key: "America/Punta_Arenas" },
	{ value: "(GMT-03:00) Recife", key: "America/Recife" },
	{ value: "(GMT-03:00) Rothera", key: "Antarctica/Rothera" },
	{ value: "(GMT-03:00) Salvador", key: "America/Bahia" },
	{ value: "(GMT-03:00) Santiago", key: "America/Santiago" },
	{ value: "(GMT-03:00) Stanley", key: "Atlantic/Stanley" },
	{ value: "(GMT-02:00) Noronha", key: "America/Noronha" },
	{ value: "(GMT-02:00) Sao Paulo", key: "America/Sao_Paulo" },
	{ value: "(GMT-02:00) South Georgia", key: "Atlantic/South_Georgia" },
	{ value: "(GMT-01:00) Azores", key: "Atlantic/Azores" },
	{ value: "(GMT-01:00) Cape Verde", key: "Atlantic/Cape_Verde" },
	{ value: "(GMT-01:00) Scoresbysund", key: "America/Scoresbysund" },
	{ value: "(GMT+00:00) Abidjan", key: "Africa/Abidjan" },
	{ value: "(GMT+00:00) Accra", key: "Africa/Accra" },
	{ value: "(GMT+00:00) Bissau", key: "Africa/Bissau" },
	{ value: "(GMT+00:00) Canary Islands", key: "Atlantic/Canary" },
	{ value: "(GMT+00:00) Casablanca", key: "Africa/Casablanca" },
	{ value: "(GMT+00:00) Danmarkshavn", key: "America/Danmarkshavn" },
	{ value: "(GMT+00:00) Dublin", key: "Europe/Dublin" },
	{ value: "(GMT+00:00) El Aaiun", key: "Africa/El_Aaiun" },
	{ value: "(GMT+00:00) Faeroe", key: "Atlantic/Faroe" },
	{ value: "(GMT+00:00) GMT (no daylight saving)", key: "Etc/GMT" },
	{ value: "(GMT+00:00) Lisbon", key: "Europe/Lisbon" },
	{ value: "(GMT+00:00) London", key: "Europe/London" },
	{ value: "(GMT+00:00) Monrovia", key: "Africa/Monrovia" },
	{ value: "(GMT+00:00) Reykjavik", key: "Atlantic/Reykjavik" },
	{ value: "UTC", key: "UTC" },
	{ value: "(GMT+01:00) Algiers", key: "Africa/Algiers" },
	{ value: "(GMT+01:00) Amsterdam", key: "Europe/Amsterdam" },
	{ value: "(GMT+01:00) Andorra", key: "Europe/Andorra" },
	{ value: "(GMT+01:00) Berlin", key: "Europe/Berlin" },
	{ value: "(GMT+01:00) Brussels", key: "Europe/Brussels" },
	{ value: "(GMT+01:00) Budapest", key: "Europe/Budapest" },
	{ value: "(GMT+01:00) Central European Time - Belgrade", key: "Europe/Belgrade" },
	{ value: "(GMT+01:00) Central European Time - Prague", key: "Europe/Prague" },
	{ value: "(GMT+01:00) Ceuta", key: "Africa/Ceuta" },
	{ value: "(GMT+01:00) Copenhagen", key: "Europe/Copenhagen" },
	{ value: "(GMT+01:00) Gibraltar", key: "Europe/Gibraltar" },
	{ value: "(GMT+01:00) Lagos", key: "Africa/Lagos" },
	{ value: "(GMT+01:00) Luxembourg", key: "Europe/Luxembourg" },
	{ value: "(GMT+01:00) Madrid", key: "Europe/Madrid" },
	{ value: "(GMT+01:00) Malta", key: "Europe/Malta" },
	{ value: "(GMT+01:00) Monaco", key: "Europe/Monaco" },
	{ value: "(GMT+01:00) Ndjamena", key: "Africa/Ndjamena" },
	{ value: "(GMT+01:00) Oslo", key: "Europe/Oslo" },
	{ value: "(GMT+01:00) Paris", key: "Europe/Paris" },
	{ value: "(GMT+01:00) Rome", key: "Europe/Rome" },
	{ value: "(GMT+01:00) Stockholm", key: "Europe/Stockholm" },
	{ value: "(GMT+01:00) Tirane", key: "Europe/Tirane" },
	{ value: "(GMT+01:00) Tunis", key: "Africa/Tunis" },
	{ value: "(GMT+01:00) Vienna", key: "Europe/Vienna" },
	{ value: "(GMT+01:00) Warsaw", key: "Europe/Warsaw" },
	{ value: "(GMT+01:00) Zurich", key: "Europe/Zurich" },
	{ value: "(GMT+02:00) Amman", key: "Asia/Amman" },
	{ value: "(GMT+02:00) Athens", key: "Europe/Athens" },
	{ value: "(GMT+02:00) Beirut", key: "Asia/Beirut" },
	{ value: "(GMT+02:00) Bucharest", key: "Europe/Bucharest" },
	{ value: "(GMT+02:00) Cairo", key: "Africa/Cairo" },
	{ value: "(GMT+02:00) Chisinau", key: "Europe/Chisinau" },
	{ value: "(GMT+02:00) Damascus", key: "Asia/Damascus" },
	{ value: "(GMT+02:00) Gaza", key: "Asia/Gaza" },
	{ value: "(GMT+02:00) Helsinki", key: "Europe/Helsinki" },
	{ value: "(GMT+02:00) Jerusalem", key: "Asia/Jerusalem" },
	{ value: "(GMT+02:00) Johannesburg", key: "Africa/Johannesburg" },
	{ value: "(GMT+02:00) Khartoum", key: "Africa/Khartoum" },
	{ value: "(GMT+02:00) Kiev", key: "Europe/Kiev" },
	{ value: "(GMT+02:00) Maputo", key: "Africa/Maputo" },
	{ value: "(GMT+02:00) Moscow-01 - Kaliningrad", key: "Europe/Kaliningrad" },
	{ value: "(GMT+02:00) Nicosia", key: "Asia/Nicosia" },
	{ value: "(GMT+02:00) Riga", key: "Europe/Riga" },
	{ value: "(GMT+02:00) Sofia", key: "Europe/Sofia" },
	{ value: "(GMT+02:00) Tallinn", key: "Europe/Tallinn" },
	{ value: "(GMT+02:00) Tripoli", key: "Africa/Tripoli" },
	{ value: "(GMT+02:00) Vilnius", key: "Europe/Vilnius" },
	{ value: "(GMT+02:00) Windhoek", key: "Africa/Windhoek" },
	{ value: "(GMT+03:00) Baghdad", key: "Asia/Baghdad" },
	{ value: "(GMT+03:00) Istanbul", key: "Europe/Istanbul" },
	{ value: "(GMT+03:00) Minsk", key: "Europe/Minsk" },
	{ value: "(GMT+03:00) Moscow+00 - Moscow", key: "Europe/Moscow" },
	{ value: "(GMT+03:00) Nairobi", key: "Africa/Nairobi" },
	{ value: "(GMT+03:00) Qatar", key: "Asia/Qatar" },
	{ value: "(GMT+03:00) Riyadh", key: "Asia/Riyadh" },
	{ value: "(GMT+03:00) Syowa", key: "Antarctica/Syowa" },
	{ value: "(GMT+03:30) Tehran", key: "Asia/Tehran" },
	{ value: "(GMT+04:00) Baku", key: "Asia/Baku" },
	{ value: "(GMT+04:00) Dubai", key: "Asia/Dubai" },
	{ value: "(GMT+04:00) Mahe", key: "Indian/Mahe" },
	{ value: "(GMT+04:00) Mauritius", key: "Indian/Mauritius" },
	{ value: "(GMT+04:00) Moscow+01 - Samara", key: "Europe/Samara" },
	{ value: "(GMT+04:00) Reunion", key: "Indian/Reunion" },
	{ value: "(GMT+04:00) Tbilisi", key: "Asia/Tbilisi" },
	{ value: "(GMT+04:00) Yerevan", key: "Asia/Yerevan" },
	{ value: "(GMT+04:30) Kabul", key: "Asia/Kabul" },
	{ value: "(GMT+05:00) Aqtau", key: "Asia/Aqtau" },
	{ value: "(GMT+05:00) Aqtobe", key: "Asia/Aqtobe" },
	{ value: "(GMT+05:00) Ashgabat", key: "Asia/Ashgabat" },
	{ value: "(GMT+05:00) Dushanbe", key: "Asia/Dushanbe" },
	{ value: "(GMT+05:00) Karachi", key: "Asia/Karachi" },
	{ value: "(GMT+05:00) Kerguelen", key: "Indian/Kerguelen" },
	{ value: "(GMT+05:00) Maldives", key: "Indian/Maldives" },
	{ value: "(GMT+05:00) Mawson", key: "Antarctica/Mawson" },
	{ value: "(GMT+05:00) Moscow+02 - Yekaterinburg", key: "Asia/Yekaterinburg" },
	{ value: "(GMT+05:00) Tashkent", key: "Asia/Tashkent" },
	{ value: "(GMT+05:30) Colombo", key: "Asia/Colombo" },
	{ value: "(GMT+05:30) India Standard Time", key: "Asia/Calcutta" },
	{ value: "(GMT+05:45) Kathmandu", key: "Asia/Kathmandu" },
	{ value: "(GMT+06:00) Almaty", key: "Asia/Almaty" },
	{ value: "(GMT+06:00) Bishkek", key: "Asia/Bishkek" },
	{ value: "(GMT+06:00) Chagos", key: "Indian/Chagos" },
	{ value: "(GMT+06:00) Dhaka", key: "Asia/Dhaka" },
	{ value: "(GMT+06:00) Moscow+03 - Omsk", key: "Asia/Omsk" },
	{ value: "(GMT+06:00) Thimphu", key: "Asia/Thimphu" },
	{ value: "(GMT+06:00) Vostok", key: "Antarctica/Vostok" },
	{ value: "(GMT+06:30) Cocos", key: "Indian/Cocos" },
	{ value: "(GMT+06:30) Rangoon", key: "Asia/Yangon" },
	{ value: "(GMT+07:00) Bangkok", key: "Asia/Bangkok" },
	{ value: "(GMT+07:00) Christmas", key: "Indian/Christmas" },
	{ value: "(GMT+07:00) Davis", key: "Antarctica/Davis" },
	{ value: "(GMT+07:00) Hanoi", key: "Asia/Saigon" },
	{ value: "(GMT+07:00) Hovd", key: "Asia/Hovd" },
	{ value: "(GMT+07:00) Jakarta", key: "Asia/Jakarta" },
	{ value: "(GMT+07:00) Moscow+04 - Krasnoyarsk", key: "Asia/Krasnoyarsk" },
	{ value: "(GMT+08:00) Brunei", key: "Asia/Brunei" },
	{ value: "(GMT+08:00) China Time - Beijing", key: "Asia/Shanghai" },
	{ value: "(GMT+08:00) Choibalsan", key: "Asia/Choibalsan" },
	{ value: "(GMT+08:00) Hong Kong", key: "Asia/Hong_Kong" },
	{ value: "(GMT+08:00) Kuala Lumpur", key: "Asia/Kuala_Lumpur" },
	{ value: "(GMT+08:00) Macau", key: "Asia/Macau" },
	{ value: "(GMT+08:00) Makassar", key: "Asia/Makassar" },
	{ value: "(GMT+08:00) Manila", key: "Asia/Manila" },
	{ value: "(GMT+08:00) Moscow+05 - Irkutsk", key: "Asia/Irkutsk" },
	{ value: "(GMT+08:00) Singapore", key: "Asia/Singapore" },
	{ value: "(GMT+08:00) Taipei", key: "Asia/Taipei" },
	{ value: "(GMT+08:00) Ulaanbaatar", key: "Asia/Ulaanbaatar" },
	{ value: "(GMT+08:00) Western Time - Perth", key: "Australia/Perth" },
	{ value: "(GMT+08:30) Pyongyang", key: "Asia/Pyongyang" },
	{ value: "(GMT+09:00) Dili", key: "Asia/Dili" },
	{ value: "(GMT+09:00) Jayapura", key: "Asia/Jayapura" },
	{ value: "(GMT+09:00) Moscow+06 - Yakutsk", key: "Asia/Yakutsk" },
	{ value: "(GMT+09:00) Palau", key: "Pacific/Palau" },
	{ value: "(GMT+09:00) Seoul", key: "Asia/Seoul" },
	{ value: "(GMT+09:00) Tokyo", key: "Asia/Tokyo" },
	{ value: "(GMT+09:30) Central Time - Darwin", key: "Australia/Darwin" },
	{ value: "(GMT+10:00) Dumont D'Urville", key: "Antarctica/DumontDUrville" },
	{ value: "(GMT+10:00) Eastern Time - Brisbane", key: "Australia/Brisbane" },
	{ value: "(GMT+10:00) Guam", key: "Pacific/Guam" },
	{ value: "(GMT+10:00) Moscow+07 - Vladivostok", key: "Asia/Vladivostok" },
	{ value: "(GMT+10:00) Port Moresby", key: "Pacific/Port_Moresby" },
	{ value: "(GMT+10:00) Truk", key: "Pacific/Chuuk" },
	{ value: "(GMT+10:30) Central Time - Adelaide", key: "Australia/Adelaide" },
	{ value: "(GMT+11:00) Casey", key: "Antarctica/Casey" },
	{ value: "(GMT+11:00) Eastern Time - Hobart", key: "Australia/Hobart" },
	{ value: "(GMT+11:00) Eastern Time - Melbourne, Sydney", key: "Australia/Sydney" },
	{ value: "(GMT+11:00) Efate", key: "Pacific/Efate" },
	{ value: "(GMT+11:00) Guadalcanal", key: "Pacific/Guadalcanal" },
	{ value: "(GMT+11:00) Kosrae", key: "Pacific/Kosrae" },
	{ value: "(GMT+11:00) Moscow+08 - Magadan", key: "Asia/Magadan" },
	{ value: "(GMT+11:00) Norfolk", key: "Pacific/Norfolk" },
	{ value: "(GMT+11:00) Noumea", key: "Pacific/Noumea" },
	{ value: "(GMT+11:00) Ponape", key: "Pacific/Pohnpei" },
	{ value: "(GMT+12:00) Funafuti", key: "Pacific/Funafuti" },
	{ value: "(GMT+12:00) Kwajalein", key: "Pacific/Kwajalein" },
	{ value: "(GMT+12:00) Majuro", key: "Pacific/Majuro" },
	{ value: "(GMT+12:00) Moscow+09 - Petropavlovsk-Kamchatskiy", key: "Asia/Kamchatka" },
	{ value: "(GMT+12:00) Nauru", key: "Pacific/Nauru" },
	{ value: "(GMT+12:00) Tarawa", key: "Pacific/Tarawa" },
	{ value: "(GMT+12:00) Wake", key: "Pacific/Wake" },
	{ value: "(GMT+12:00) Wallis", key: "Pacific/Wallis" },
	{ value: "(GMT+13:00) Auckland", key: "Pacific/Auckland" },
	{ value: "(GMT+13:00) Enderbury", key: "Pacific/Enderbury" },
	{ value: "(GMT+13:00) Fakaofo", key: "Pacific/Fakaofo" },
	{ value: "(GMT+13:00) Fiji", key: "Pacific/Fiji" },
	{ value: "(GMT+13:00) Tongatapu", key: "Pacific/Tongatapu" },
	{ value: "(GMT+14:00) Apia", key: "Pacific/Apia" },
	{ value: "(GMT+14:00) Kiritimati", key: "Pacific/Kiritimati" }
];


export default timezones;
